"""Emit symbol tables for the openMSX debugger and assemblers.

openMSX accepts several formats. We emit two:

  * openmsx — the "tniASM"-style symbol file openMSX's debugger loads natively:
        SYMBOL: equ #NNNN
    (also accepts $NNNN and 0xNNNN; we use #NNNN which is the most
    widely-supported MSX-scene convention)

  * sjasm — the "label: equ 0xNNNN" form emitted by sjasm/sjasmplus/pasmo.
"""

from __future__ import annotations

from typing import Callable

from .parser import KB, SymbolEntry


def _openmsx_line(e: SymbolEntry) -> str:
    return f"{e.name}: equ #{e.address:04X}"


def _sjasm_line(e: SymbolEntry) -> str:
    return f"{e.name}: equ 0x{e.address:04X}"


EMITTERS: dict[str, Callable[[SymbolEntry], str]] = {
    "openmsx": _openmsx_line,
    "sjasm": _sjasm_line,
}


def emit(kb: KB, fmt: str) -> str:
    if fmt not in EMITTERS:
        raise ValueError(
            f"unknown format {fmt!r}; known: {sorted(EMITTERS)}"
        )
    fn = EMITTERS[fmt]
    # Sort by address for deterministic diffs
    lines = [
        fn(e)
        for e in sorted(kb.entries, key=lambda e: e.address)
        # constants without a meaningful address are skipped for the symbol file
        if e.kind != "constant" or e.address != 0
    ]
    header = [
        f"; Generated by zanackb — DO NOT EDIT",
        f"; Format: {fmt}",
        f"; {len(lines)} symbols",
        "",
    ]
    return "\n".join(header + lines) + "\n"
